[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_THEME = "bigspring"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200 